### ISSUE TITLE
server.js - TypeError: Cannot read property 'year' of undefined

### ISSUE THREAD

**Issue by larrylzhao** [larrylzhao/therollingcars#4]
{ make: 'asd b9',
  model: 'fads d 9',
  miles: '123',
  year: '1234',
  color: 'ble',
  price: '123',
  cost: '13' }
Backend validation of the inventory input data
TypeError: Cannot read property 'year' of undefined
    at validateInventoryInputData (/Users/larryzhao/Dropbox/CU/ASE/assignment2/therollingcars/server.js:78:57)
    at app.delete.id (/Users/larryzhao/Dropbox/CU/ASE/assignment2/therollingcars/server.js:34:7)
    at Layer.handle [as handle_request] (/Users/larryzhao/Dropbox/CU/ASE/assignment2/therollingcars/node_modules/express/lib/router/layer.js:95:5)

**Comment by larrylzhao** [comment]
the property name for year had an extra "vehicle" field in the validation
    if (!validateInputs.nodeValidateNumber(req.body.vehicle.year, 4, 4, "year")){ return false; }
